drop policy "Fetch animes for users" on "public"."animes";

create table "public"."anime_vod" (
    "id" bigint generated by default as identity not null,
    "anime_id" bigint not null,
    "vod_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."anime_vod" enable row level security;

alter table "public"."animes" drop column "vod";

CREATE UNIQUE INDEX anime_vod_pkey ON public.anime_vod USING btree (id);

alter table "public"."anime_vod" add constraint "anime_vod_pkey" PRIMARY KEY using index "anime_vod_pkey";

alter table "public"."anime_vod" add constraint "public_anime_vod_anime_id_fkey" FOREIGN KEY (anime_id) REFERENCES animes(id) not valid;

alter table "public"."anime_vod" validate constraint "public_anime_vod_anime_id_fkey";

alter table "public"."anime_vod" add constraint "public_anime_vod_vod_id_fkey" FOREIGN KEY (vod_id) REFERENCES vod_services(id) not valid;

alter table "public"."anime_vod" validate constraint "public_anime_vod_vod_id_fkey";

grant delete on table "public"."anime_vod" to "anon";

grant insert on table "public"."anime_vod" to "anon";

grant references on table "public"."anime_vod" to "anon";

grant select on table "public"."anime_vod" to "anon";

grant trigger on table "public"."anime_vod" to "anon";

grant truncate on table "public"."anime_vod" to "anon";

grant update on table "public"."anime_vod" to "anon";

grant delete on table "public"."anime_vod" to "authenticated";

grant insert on table "public"."anime_vod" to "authenticated";

grant references on table "public"."anime_vod" to "authenticated";

grant select on table "public"."anime_vod" to "authenticated";

grant trigger on table "public"."anime_vod" to "authenticated";

grant truncate on table "public"."anime_vod" to "authenticated";

grant update on table "public"."anime_vod" to "authenticated";

grant delete on table "public"."anime_vod" to "service_role";

grant insert on table "public"."anime_vod" to "service_role";

grant references on table "public"."anime_vod" to "service_role";

grant select on table "public"."anime_vod" to "service_role";

grant trigger on table "public"."anime_vod" to "service_role";

grant truncate on table "public"."anime_vod" to "service_role";

grant update on table "public"."anime_vod" to "service_role";

create policy "Enable read access for all users"
on "public"."animes"
as permissive
for select
to public
using (true);



